# Uncomment this line to define a global platform for your project
platform :ios, '9.2'
# Uncomment this line if you're using Swift
use_frameworks!

inhibit_all_warnings!

target 'Museek' do

pod 'ModelRocket'
pod 'Alamofire'

end

